# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZOMan2iV2QCal95UN0z31CBUgSNWTKz5
"""

# Check if two words are anagrams
def find_anagrams(word, anagram):
  if(sorted(word)== sorted(anagram)):
    return True
  else:
    return False
# Example 
find_anagrams("hello", "check")